language: java
env:
  global: 
    secure: "Q0OReCmeW8OoxdvLEAc5wawYMLhApNSB4kfi2RMjye3XpVn7vnWRK+fCcgeW\nIGoo6mCgYBs7Oc4SVEQI82gV3Ii0R5Fi2AKroayzgv0lainC0phbjg9kgDUw\nXavnNlQSiEy5vuFrhhZNu2nZnHkeccFQfnLhb/bLxcLJove8R7I="
script:
# Generate Javadocs
 - 'bash -c "javadoc -d ./out/common -sourcepath ./common -subpackages net.minecraftforge || true"'
 - 'bash -c "javadoc -d ./out/client -sourcepath ./client -subpackages net.minecraftforge:ibxm:paulscode || true"'
# Move docs out of the git repo
 - 'mv ./out ../out'
# Switch to the Github pages branch
 - 'git reset --hard'
 - 'git checkout gh-pages'
# Move docs into the git repo
 - 'rm -rf ./out'
 - 'mv -f ../out ./out'
# Commit all docs
 - 'git add *'
 - 'git commit -m "Updating Javadoc from Travis-CI"'

 - 'echo ${GHUSER}'

# Setup git to push back to github
 - 'git remote add pushto https://github.com/cspotcode/MinecraftForge.git'
 - 'git remote -v'
# - 'echo "#!/bin/bash" > askpass.sh'
# - 'echo "echo ${GHPASS}" >> askpass.sh'
# - 'chmod +x askpass.sh'
# - 'sudo apt-get install realpath'
# - 'git config --add core.askpass "`realpath askpass.sh`"'
# - 'git config --list'
# - './askpass.sh'
 - 'echo "machine github.com" >> ~/.netrc'
 - 'echo "login ${GHUSER}" >> ~/.netrc'
 - 'echo "password ${GHPASS}" >> ~/.netrc'

# Push docs to Github
 - 'git push -v pushto gh-pages'
